[package]
name = "open-transcribe-tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "1", features = ["api-all"] }

[build-dependencies]
tauri-build = { version = "1" }
