[package]
name = "open-transcribe"
version = "2.0.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "1", features = [] }

[build-dependencies]
tauri-build = { version = "1", features = [] }
